package com.example.honeypotmanagement.enums;

public enum AttackType {
    SQL_INJECTION,
    XSS_ATTACK,
    BRUTE_FORCE_LOGIN,
    SSH_BRUTE_FORCE,
    DIRECTORY_TRAVERSAL,
    COMMAND_INJECTION,
    UNAUTHORIZED_ACCESS,
    PORT_SCAN,
    DOS_ATTACK,
    MALWARE_UPLOAD,
    DATABASE_PROBE,
    API_ABUSE,
    INFORMATIONAL
}
